### ISSUE TITLE
Potential problem with connection management

### ISSUE THREAD

**Issue by skyleraustin** [dsuryd/dotNetify-react-native-demo#10] opened 2018-11-25 20:19 UTC
I am having an issue when I destroy all view models on the client-side, connections are not terminated on the server. I am seeing that Dispose is called on the server-side models, but connections remain open for another ~60 seconds. Not sure if that is causing an issue, but here is what I am seeing:

(note that I am still on 3.0.1 - #7)
1) Mount component and connect view model
2) Unmount component and destroy viewmodel
3) Observe Dispose is called on server
4) Navigate to a client component that does not have a dotnetify connection
5) After ~60 seconds, observe that the dotnet server reports "request finished"
6) Navigate to a client component that has a dotnetify connection
7) Receive an error (below)

dotnet output (my own note in bold):
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://192.168.0.8:5000/dotnetify?id=udciaGwHHoxMlvz9fnw_YA
info: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.
Disposed **(output from overridden Dispose(). in this example, this happened about 5 seconds after handshake)**
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 54858.6045ms 101

RN/Expo error:
console.error: "Error: Connection disconnected with error 'Error: Websocket closed with status code: undefined (undefined)'."
__expoConsoleLog
    \node_modules\expo\src\logs\RemoteConsole.js:98:8
error
    \node_modules\react-native\Libraries\ReactNative\YellowBox.js:69:16
log
    \node_modules\dotnetify\dist\signalR-netcore.js:1883:35
<unknown>
    \node_modules\dotnetify\dist\signalR-netcore.js:3119:37
step
    \node_modules\dotnetify\dist\signalR-netcore.js:119:27
<unknown>
    \node_modules\dotnetify\dist\signalR-netcore.js:93:14
initializePromise
    \node_modules\dotnetify\dist\signalR-netcore.js:693:24
Promise
    \node_modules\dotnetify\dist\signalR-netcore.js:1113:62
__awaiter
    \node_modules\dotnetify\dist\signalR-netcore.js:89:38
onclose
    \node_modules\dotnetify\dist\signalR-netcore.js:2769:50
dispatchEvent
    \node_modules\event-target-shim\lib\event-target.js:172:43
<unknown>
    \node_modules\react-native\Libraries\WebSocket\WebSocket.js:269:27
emit
    \node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:180:12
__callFunction
    \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:351:47
<unknown>
    \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:116:26
__guardSafe
    \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115:17

**Comment by skyleraustin** [comment] 2018-11-28 04:47
The hard error is hidden in Production mode, but the app does not immediately re-establish connection to the server.
Similar repro:

1. Mount component and connect view model
2. Unmount component and destroy viewmodel
3. Observe Dispose is called on server
4. Navigate to a client component that does not have a dotnetify connection
5. After ~60 seconds, observe that the dotnet server reports "request finished"
6. Navigate to a client component that has a dotnetify connection
7. ~~Receive an error~~ Observe client vm does not have an active server connection
8. After some more time (~60 more seconds), dotnetify client goes from "disconnected" connection state to "reconnecting" and successfully re-establishes the connection and client vm becomes operational

If there are no active viewmodels on the client-side (dotnetify.react.getViewModels() is none) I can understand why dotnetify would be in a disconnected (or even retrying) state. But if the client has explicitly requested to connect another vm (dotnetify.react.connect @ step 6 above), should the framework not immediately try to establish/re-establish connection? Is it that the client framework has not yet realized that the server has closed the connection? Should the client immediately go into disconnected state when the server closes the connection?

**Comment by skyleraustin** [comment] 2018-11-28 04:55
I should also mention, this behavior is the same when the redscreen is dismissed in dev mode

**Comment by dsuryd** [comment] 2018-11-28 18:07
Try the latest version.  I couldn't reproduce on the example in this repo running on Android emulator.  If you can still reproduce, please describe the steps using the repo example.

**Comment by skyleraustin** [comment] 2018-11-29 04:37
I am having a hard time reproducing the issue in the example repo, but there is still something here. Not quite sure what at the moment.

**Comment by skyleraustin** [comment] 2018-11-29 04:45
In my app I am able to get into a state where the server has closed the connection, the client has destroyed all vms, and I navigate to a component that wants a new vm connection (dotnetify.react.connect) and the client does not establish a connection nor produces any errors. This leaves me with a component that appears functional but doesn't have any server interaction. I realize this is obscure and I am not giving you much to help with, but any thoughts you have would be appreciated.

**Comment by dsuryd** [comment] 2018-11-29 05:47
Something in your app lead to that state.  Can you find a way to modify
this example repo to mimic it?

**Comment by dsuryd** [comment] 2018-11-30 03:40
Rereading the steps, seems that the server has terminated the particular connection id, but somehow the SignalR client still holds on to it and use it for the next VM, and that's why it's timing out waiting to use a terminated connection.    Can you add DeveloperLogging middleware and check if you see something like this at step 5?
```
[dotNetify] connId=0EO1erJAHPTdnxsRcd6zWg type=OnDisconnected
```

**Comment by skyleraustin** [comment] 2018-11-30 04:18
> Something in your app lead to that state. Can you find a way to modify this example repo to mimic it?

I will work on this

**Comment by skyleraustin** [comment] 2018-11-30 04:24
> Rereading the steps, seems that the server has terminated the particular connection id, but somehow the SignalR client still holds on to it and use it for the next VM, and that's why it's timing out waiting to use a terminated connection. Can you add DeveloperLogging middleware and check if you see something like this at step 5?
> 
> ```
> [dotNetify] connId=0EO1erJAHPTdnxsRcd6zWg type=OnDisconnected
> ```

I have had the UseDeveloperLogging middleware enabled since I started using the framework and have not encountered output like that.

However, in my testing just now, I encountered an exception that I have not seen in most of my other testing. It remains in this state for some time (again about 60 seconds) with unusable client until connection is reestablished

(again, bold is my notes)

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://192.168.0.8:5000/dotnetify/negotiate  0
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.2538ms 200 application/json
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://192.168.0.8:5000/dotnetify?id=7R-R_FmJT6GgFR9Xr_Tqvg
info: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.
Disposed **(client vms destroyed because app is sent to background)**
**app is currently on a component that doesnt use dotnetify**
**about 30 seconds later**
info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
      Connection id "0HLIMF7535QQG" communication error.
System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitable.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 49904.9288ms 101
**after another 60 seconds or so with a dead client component, connection is re-established**

**Comment by skyleraustin** [comment] 2018-11-30 04:45
My scenario aside, what is the expected behavior when something like this is done when the application is done with dotnetify:

`dotnetify.react.getViewModels().forEach(vm => {
    vm.$destroy()
});`

and then when it needs it again (no matter how long it has been since disposal), a new vm is connected? Does the client framework (have the ability to?) check if an operating server connection is open? 

If not, is there a good way to confirm dotnetify has an open connection before attempting to connect vms?

Based on what I am experiencing, dotnetify.react.connect() is not "safe".

**Comment by dsuryd** [comment] 2018-11-30 19:11
> Disposed **(client vms destroyed because app is sent to background)**
> **about 30 seconds later**

Do your repro steps always involve sending app to the background?  The iOS will kill SignalR connection in this mode, not sure about Android.  The 30 seconds would then be the [default signalR timeout](https://docs.microsoft.com/en-us/javascript/api/@aspnet/signalr/hubconnection?view=signalr-js-latest#servertimeoutinmilliseconds).

> **after another 60 seconds or so with a dead client component, connection is re-established**

Try reducing reconnection delay using `dotnetify.hub.reconnectDelay`.
As an experiment, see if manually stopping prev connection before connecting helps:
```
if (dotnetify.hub.isHubStarted())
{
   dotnetify.hub._connection.stop();
   dotnetify.hub._hub = null;
}
```

>My scenario aside, what is the expected behavior when something like this is done when the application is done with dotnetify:
>
>dotnetify.react.getViewModels().forEach(vm => { vm.$destroy() });
>
DotNetify's operating assumption is that once a signalR connection is established, it is for the lifetime of the app.   Destroying all VMs won't do anything to the connection.

>and then when it needs it again (no matter how long it has been since disposal), a new vm is connected? Does the client framework (have the ability to?) check if an operating server connection is open?
>
It doesn't need to check.   It simply uses the Promise object returned by the SignalR client and starts sending requests when the promise is resolved, and retry starting the connection if rejected.  

>If not, is there a good way to confirm dotnetify has an open connection before attempting to connect vms?

The app should use `dotnetify.connectionStateHandler` to access the connection events and do its own robustness strategy to deal with connection problems.

**Comment by skyleraustin** [comment] 2018-11-30 23:33
Thank you for the responses. I will do more testing this weekend.

**Comment by skyleraustin** [comment] 2018-12-02 18:12
I am getting dotnetify.hub.isHubStarted() is not a function on 3.3.1. I am looking into it but if you are around...

**Comment by skyleraustin** [comment] 2018-12-02 18:44
A little different than the documentation (http://dotnetify.net/core/api/connection), but here is my reconnectDelay and reconnectRetry:
reconnectDelay: [2, 5, 10]
reconnectRetry: null

As noted above, dotnetify.hub.isHubStarted() does not work, but dotnetify.hub.isConnected seems to. Stopping and dropping the hub in your example does force a disconnect, but an immediate reconnect does not occur when dotnetify.react.connect is used. Same problem. Dead component until reconnection occurs.

I will continue experimenting with this new information

**Comment by dsuryd** [comment] 2018-12-02 19:19
Sorry it’s dotnetify.isHubStarted.

**Comment by skyleraustin** [comment] 2018-12-02 19:39
I think I am getting closer. When my app gets sent to the background, I would prefer to disconnect dotnetify and ensure that it does not attempt to reconnect until the app re-enters the foreground AND a component is loaded that wants a dotnetify vm.

```
if (dotnetify.isHubStarted) {
        dotnetify.hub.reconnectRetry = -1;
        dotnetify.hub._connection.stop();
        dotnetify.hub._hub = null;
}
```

From looking at dotnetify.js:1648, setting `dotnetify.hub.reconnectRetry = -1;` was the only was I could see to effectively disable reconnection. Is there currently a more elegant way to accomplish this?

When the app returns to the foreground, I am restoring `dotnetify.hub.reconnectRetry = null;`, and when `dotnetify.react.connect` occurs, the connection is successfully restored.

THAT ALL SAID.. 

After the dotnetify connection state goes to disconnected (and then terminated), the following error is thrown:

> console.error: "Error: Connection disconnected with error 'Error: Websocket closed with status code: 1001 (Stream end encountered)'."
> 
> __expoConsoleLog
>     \node_modules\expo\build\logs\RemoteConsole.js:89:37
> error
>     \node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8
> log
>     \node_modules\@aspnet\signalr\dist\cjs\Utils.js:196:34
> <unknown>
>     \node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:354:36
> step
>     \node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:34:27
> <unknown>
>     \node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:9:13
> tryCallTwo
>     \node_modules\promise\setimmediate\core.js:45:7
> doResolve
>     \node_modules\promise\setimmediate\core.js:200:23
> Promise
>     \node_modules\promise\setimmediate\core.js:66:12
> <unknown>
>     \node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:5:36
> onclose
>     \node_modules\@aspnet\signalr\dist\cjs\WebSocketTransport.js:96:58
> dispatchEvent
>     \node_modules\event-target-shim\lib\event-target.js:172:43
> <unknown>
>     \node_modules\react-native\Libraries\WebSocket\WebSocket.js:276:10
> emit
>     \node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:191:12
> __callFunction
>     \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:349:47
> <unknown>
>     \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:106:26
> __guard
>     \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10
> callFunctionReturnFlushedQueue
>     \node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:105:17
>

**Comment by dsuryd** [comment] 2018-12-03 04:37
> if (dotnetify.isHubStarted) {
        dotnetify.hub.reconnectRetry = -1;
        dotnetify.hub._connection.stop();
        dotnetify.hub._hub = null;
}
From looking at dotnetify.js:1648, setting dotnetify.hub.reconnectRetry = -1; was the only was I could see to effectively disable reconnection. Is there currently a more elegant way to accomplish this?

I can add a new API `dotnetify.disconnect()` to do all the above.

> After the dotnetify connection state goes to disconnected (and then terminated), the following error is thrown:
console.error: "Error: Connection disconnected with error 'Error: Websocket closed with status code: 1001 (Stream end encountered)'."

Couldn't reproduce this.  I added a new page to the example repo which disconnects dotNetify on mount.  Navigated to the page, I could see the server log the disconnected event.  Went back to the page with dotNetify; it immediately connected without error.

**Comment by skyleraustin** [comment] 2018-12-04 03:33
I just did the same with the example repo and am able to reproduce the error. Also confirmed the offending line is dotnetify.hub._connection.stop();.

Perhaps it is either something with iOS or my environment. Unfortunately, I do not have a way to confirm on Android. Do you have a way to test on iOS?

I can't find many other leads, but there is this unresolved issue [here](https://github.com/aspnet/SignalR/issues/2556)

**Comment by dkorth** [comment] 2021-02-16 23:12
Is this issue still a problem? I have had this problem since upgrading to dotnet core 3.1 and dotnetify 3.6.2 and haven't been able to recreate it from example application. The websocket disconnects and refreshing the page doesn't do anything until I logout of the application. It occurs after the token expires and hitting refresh on the page. It is only happening in production.

**Comment by dsuryd** [comment] 2021-02-17 01:27
@dkorth I was never able to reproduce this issue and my resources were limited to testing on emulators.  But is yours a react-native app, and if so how did you refresh the page on the app?

**Comment by dsuryd** [comment] 2021-03-02 06:20
Closing this as there's no follow-up.

**Closed by dsuryd** 2021-03-02 06:20 UTC
